### ISSUE TITLE
Consolidate CCOLAMD wrapper from IncrementalInference.jl?

### ISSUE THREAD

**Issue by dehann** [JuliaSmoothOptimizers/AMD.jl#36]
Hi, I have wrapper code available for using CCOLAMD -- it's probably best to consolidate that file here?

https://github.com/JuliaRobotics/IncrementalInference.jl/blob/870e518fc7e808b911bcd50682a2f786a793a80b/src/ccolamd.jl

Not sure about license compatibility though, having a more permissive (non-copyleft) license is desirable in many cases.  Also adding @andreasnoack as the orginal author of this `ccolamd.jl` file.

**Comment by dehann** [comment]
Just to clarify on license -- we have strong reasoning for keeping permissive licenses throughout specific slices of the code base.  Just copying here from https://github.com/JuliaRobotics/IncrementalInference.jl/issues/980#issue-724728894

> One solution might be to have JuliaRobotics/VariableEliminationOrderings.jl provides a mechanism to include more methods depending on the desired license restrictions.

**Comment by dpo** [comment]
Thank you. We're open to relicensing this package under the MIT license. Would that work for you?

**Comment by amontoison** [comment]
@dehann I generated the wrappers for `amd`, `camd`, `colamd` and `ccolamd` with #61 if you are still interested to add your code here.

**Comment by dehann** [comment]
Hi @amontoison , I looked at the PR and your ccolamd code seems to cover it.  The code I have does roughly the same thing but doesn't have the error states etc.  My code might also be a bit stale as it was written on Julia 0.6.  I'd say go ahead with 61 thanks!  That would also close this issue.

**Comment by amontoison** [comment]
Thanks for your answer @dehann. I merged #61, I will do a new release.
